#!/usr/bin/python
#
# TODO:
#   -parse offer
#   -parse shipping
#   -calculate total
#   -SMS notify
#

import httplib,lxml,re

BOOKID='1841499897'
SERVER={'EUR':'www.amazon.de','GBP':'www.amazon.co.uk'}

#----------------------------

def currency(curr):
    try:
        c = httplib.HTTPConnection('www.cnb.cz',timeout=15)
        c.request('GET','/cs/financni_trhy/devizovy_trh/kurzy_devizoveho_trhu/denni_kurz.txt')
        r = c.getresponse()
        if r.status == 200:
            for LINE in r.read().split('\n'):
                if curr in LINE:
                    value = float(re.sub(',','.',re.sub('.*\|(.*)$','\\1',LINE)))
        c.close()
        return value
    except: pass
    return ''

#print currency('EUR')
#print currency('GBP')

def parse_offer(curr):
    #try:
        c = httplib.HTTPSConnection(SERVER[curr],'443',timeout=15)
        c.request('GET','/gp/offer-listing/' + BOOKID + '/')
        r = c.getresponse()
        if r.status == 200:
            data = r.read()
	    for LINE in data.split('\n'):
                if 'olpOfferPrice' in LINE:
                    if curr == 'EUR':
                        PRICE = float(re.sub(',','.',re.sub('.*> +EUR (.*) +.*','\\1',LINE)))
                    if curr == 'EUR':
                        PRICE = float(re.sub('.*> +\xc2\xa3(.*) +.*','\\1',LINE))# \c2\a3 => GBP
        c.close()
    #except:
    #   	print("DE parse fail.")


