#!/usr/bin/python

import poplib,smtplib,time
from email.mime.text import MIMEText

INSRV='pop3.seznam.cz'
INBOX='xxx@email.cz'
INPASS='xxx'
OUTUSR='root@root.cz'
OUTSRV='smtps21.cz.o2.com'
OUTBOX='+420xxx@sms.cz.o2.com'

msg = MIMEText('CZ Book Offer!')
msg['From'] = OUTUSR
msg['To'] = OUTBOX

TOKEN=True
NOTIFY=True

#-----------------

log = open('/var/log/book.log','a',0)

while 1:
    if time.gmtime()[4] == 30 and TOKEN:
        TOKEN = False
        try:
            s = poplib.POP3(INSRV,timeout=15)
            s.user(INBOX)
            s.pass_(INPASS)
            m = s.stat()[0]
            s.quit()
            if m > 0 and NOTIFY:
                mail = smtplib.SMTP(OUTSRV)
                mail.sendmail(OUTUSR,OUTBOX,msg.as_string())
                mail.quit()
                NOTIFY=False
                log.write(time.strftime('%d.%m.%y %H:%M') + ' Hit.\n')
            if m == 0 and not NOTIFY: NOTIFY=True
        except:
            log.write(time.strftime('%d.%m.%y %H:%M') + ' Connection error.\n')
            pass
    if time.gmtime()[4] == 31: TOKEN=True
    time.sleep(5)

log.close()

