#!/usr/bin/python
#
# Cesnet TCS APIclient
#
# Import TERENA chain cert.
#
# wget https://pki.cesnet.cz/certs/TERENA_SSL_High_Assurance_CA_3.pem
# openssl x509 -outform der -in TERENA_SSL_High_Assurance_CA_3.pem -out TERENA_SSL_High_Assurance_CA_3.crt
# mv TERENA_SSL_High_Assurance_CA_3.crt /usr/share/local/ca-certificates/
# update-ca-certificates 
#

import httplib,json,ssl

ID='31415265'
SERVER_CRT='/root/server.crt'
SERVER_KEY='/root/server.key'

REQUEST_URL='https://tcs.cesnet.cz/api/v2/certificate/request'
STATUS_URL='https://tcs.cesnet.cz/api/v2/certificate/status/' + ID

HEADER={'Content-type':'application/json'}

#--------------------------

#Setup SSL client certificate (CA => /etc/ssl/certs/) 
context = ssl.SSLContext(ssl.PROTOCOL_TLS)
context.load_cert_chain('/root/server.pem','/root/server/key')

# reqest cert
# loop request status
# write new cert
# reload services

