#!/bin/bash

DOMAIN='server.cz'
SERVER_KEY='server.key'

CSR=$(openssl req -new -sha256 -key $SERVER_KEY -subj /CN=$DOMAIN)

/usr/bin/python /root/tcs/cesnet_tcs_tiny.py \
	--client-crt /root/tcs/client.crt \
	--client-key /root/tcs/cleint.key \
	--csr /root/tcs/server.csr \
	> /tmp/server.crt || exit 1

[ -s /tmp/server.crt ] && cat /tmp/server.crt > /etc/apache2/tcs/server.crt

mv /tmp/server.crt /root/tcs/ 2> /dev/null

service apache2 restart

exit 0

