#!/bin/bash
#
# notepad to CSV press
#

if [ -n "$1" ] && [ -f "$2" ]; then
	sed -r "s/(..\...\.) (..:..) (...) \/ (..) \[(..)\]/\1$1 \2:00;\3;\4;\5/" "$2"	
else
	echo "Usage: press [year] [file]"
fi

