#!/bin/bash
#

URL='http://www.nhk.or.jp/r-news/podcast/nhkradionews.xml'
DWARF=('red.dwarf*' 'red_dwarf_12*' 'red_dwarf_11_0*' 'red_dwarf_11_1*')

if [[ "$1" != '-h' ]]; then
	killall mpg123 2> /dev/null
	killall mpg123.bin 2> /dev/null
fi

case $1 in
	-j)# Japan NHK Podcast
		mpg123 -q $(wget -q -O - $URL | grep mp3 | sed -r 's/.*(http.*mp3).*/\1/') &
	;;
	-n)# Nihongo lesson
		shift; for lesson in $@; do LIST+=" /root/nihongo/$lesson*"; done
		mpg123 -q $LIST 2> /dev/null &
	;;
	-d)# Random Red Dwarf 10/11/12 episodes
		mpg123 -q -z /root/dwarf/${DWARF[$(($RANDOM % 4))]} &
	;;
	-h)# Usage
		cat <<- EOL
			Usage: sound [OPTION]
			 -d             Red Dwarf
			 -j             NHK Podcast
			 -n <lesson ..> Nihongo lesson
			 -k             Stop
		EOL
	;;
	-k)# Stop the music
	;;
	*)# Smooth Lounge Radio
		mpg123 -q 'http://fr1.lounge-radio.com:80/lounge128.mp3' &
esac

