#!/bin/bash
#

URL='http://www.nhk.or.jp/r-news/podcast/nhkradionews.xml'
URL2='http://fr1.lounge-radio.com:80/lounge128.mp3'

if [[ "$1" != '-h' ]]; then
	killall mpg123 2> /dev/null
	killall mpg123.bin 2> /dev/null
fi

case $1 in
	-j)# Japan NHK Podcast
		mpg123 -q $(wget -q -O - $URL | grep mp3 | sed -r 's/.*(http.*mp3).*/\1/') &
	;;
	-n)# Nihongo lesson
		shift; for lesson in $@; do LIST+=" /root/nihongo/$lesson*"; done
		mpg123 -q $LIST 2> /dev/null &
	;;
	-h)# Usage
		cat <<- EOL
			Usage: sound [OPTION]
			 -j             NHK podcast
			 -n <lesson ..> Nihongo lesson
			 -h             Print usage
			 -k             Just stop music
		EOL
	;;
	-k)# Stop the music
	;;
	*)# Smooth Lounge Radio
		mpg123 -q $URL2 &
esac

