#!/usr/bin/python
#
# BEGIN:VCARD
# VERSION:2.1
# N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;O2-Hlas s.Zahr;;;
# FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:O2-Hlas s.Zahr
# TEL;CELL:+420602989898
#

import unicodedata

CSV='okasan.csv'
VCARD='okasan.vcf'

vcf = open(VCARD, 'a', 0)

with open(CSV, 'r') as csv:
	for line in csv:

		#
		# PARSE CSV
		#

		data  = line.strip().split(';')

		cell = data[1].replace('\xc2\xa0','').strip()
		mobile = data[2].replace('\xc2\xa0','').strip()

		phone=''

		if cell: phone = cell
		if mobile: phone = mobile

		name = unicodedata.normalize('NFKD', data[0].decode('utf-8')).encode('ascii','ignore').strip()

		#
		# WRITE CARD
		#

		vcf.write('BEGIN:VCARD\r\n')
		vcf.write('VERSION:2.1\r\n')
		vcf.write('N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;' + name + ';;;' + '\r\n')
		vcf.write('FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:' + name + '\r\n')
		vcf.write('TEL;CELL:' + phone + '\r\n')
		vcf.write('END:VCARD\r\n')

#vcf.close()

