#!/bin/bash
#
# VPN
#

NET='147.231.80'

case $1 in
	--start)
		if [ -n "$(pidof openvpn)" ]; then
			echo "Already running."
			exit 1
		fi
		/usr/sbin/openvpn --cd /etc/openvpn --config client.ovpn --route-up fix_route --daemon
		# Wait for routing.
		while [ -z "$(ip r | grep $NET)" ];
		do
			echo -n '.'
			sleep 1
		done
		# Done.
		echo
	;;
	--stop)
		kill -s 'SIGTERM' $(pidof openvpn) 2>/dev/null
	;;
	-h|--help|*)
		cat <<- EOL
			Usage: vpn [--start] [--stop]
			 -h --help    Print help.
			 --start      Start VPN.
			 --stop       Stop VPN.
		EOL
	;;
esac

