#!/bin/bash
#
# VPN
#

case $1 in
	--start)# Start VPN
		/usr/sbin/openvpn --cd /etc/openvpn/client --config client.ovpn --route-up fix_route --daemon
	;;
	--stop)# Stop VPN
		kill -s 'SIGTERM' $(pidof openvpn) 
	;;
	-h|--help|*)# Usage
		cat <<- EOL
			Usage: vpn [--start] [--stop]
			 -h --help    Print help.
			 --start      Start VPN.
			 --stop       Stop VPN.
		EOL
	;;
esac

